src/App.tsx, src/data/navigation.ts, src/pages/Discord.tsx
This PR introduces a "Community Discord" Link within the site's footer. It also adds a new route `/discord` that redirects to https://discord.gg/5xBQmjWm
=> feat: community discord footer link and /discord route

src/pages/government/layout.tsx
=> [FIX] UI: Government branches hover and active color

src/components/search/MeilisearchInstantSearch.css
This fix aims to improve visual fidelity for the hero section by authoring a small fix to the CSS for `src/components/search/MeilisearchInstantSearch.tsx` in `src/components/search/MeilisearchInstantSearch.css`.
=> fix: eliminate sharp edges around hero section search input

src/data/services/housing.json
When navigating to Services -> Housing -> Apply for Pag-IBIG Housing Loan, redirect link not working and should go to [here](https://www.pagibigfundservices.com/virtualpagibig/HL/Reminder.aspx).
=> fix: update pagibig housing loan application link

.editorconfig
This PR introduces a **.editorconfig** file to standardize coding styles across the project. It helps ensure consistent formatting regardless of the editor or IDE used by contributors.
The following rules are applied project-wide:
- Charset: utf-8
- Indentation style: spaces
- Indentation size: 2 spaces
- Line endings: LF (Unix/macOS style)
- Final newline: always ensured
- Trailing whitespace: automatically trimmed
- Improves readability and consistency of the codebase
- Reduces formatting-related diffs in commits
- Simplifies collaboration across different editors/IDEs
Closes: https://github.com/bettergovph/bettergov/issues/60
=> chore: add editorconfig file to maintain consistent coding styles across different IDE's or editors

README.md
The Setup section in the README.md shows the incorrect URL for cloning the project's Git repository: `https://github.com/your-org/bettergov.ph.git`. This changes the URL to `https://github.com/bettergovph/bettergov.git` which is the correct URL.
=> docs: fix repository clone URL in README

src/pages/flood-control-projects/index.tsx
Simple UI Adjustment hope that this pr help on visualization
Fix: Improved Chart Layout and Readability
1. Types of Work Chart
- Problem: Pie chart was too small with poor spacing and overlapping labels
- Solution:
-- Split into 60/40 layout (chart/legend)
-- Added scrollable legend with colored dots
-- Increased chart size and improved spacing
2. Top Contractors Chart
-Problem: Long contractor names were being cut off
-Solution:
-- Increased left margin (left: -60)
-- Adjusted font size and width for better text wrapping
-- Added interval={0} to show all labels
Prev
Update
=> fix: Types of Work & Top Contractors Chart

src/pages/philippines/history/index.tsx
- Reversed the timeline to show newest events first (starting with Independence Era) since that's how timelines typically work
- Made the timeline actually look like a timeline with visual elements
- Flipped the order: Independence Era → American Period → Spanish Era → Pre-Colonial
- Added a vertical line connecting all timeline events
- Added circular nodes with icons for each time period
- Better visual cards with period badges showing the dates
- Fixed some linting issues (unused imports, quote consistency)
=> fix: reverse timeline order to show newest events first

src/pages/philippines/map/index.tsx
**Description:**
This PR fixes an issue where the selected region overflows its container on the map page in desktop.
**Issue:**
**Fix: Desktop View**
**Mobile View**
**Notes:**
- No changes to business logic this PR only affects UI layout.
- Fixes happen only in the map page.
=> fix(ui): resolve selected region overflow in map page

src/pages/government/constitutional/index.tsx
The current implementation shows the slug, which is unnecessary
Just removing it here so its cleaner
=> Remove unnecessary slug text

.github/workflows/build-test.yml, src/pages/philippines/map/index.tsx
**Description:**
- This PR addresses an issue with the map’s zoom functionality:
- React Leaflet’s default zoom control was removed to avoid duplication.
**Issue:**
- The search bar overlapped with the zoom controls.
- Both the default Leaflet zoom controls and custom zoom controls were displayed.
- The custom zoom buttons were not functional.
**Fix:**
- Removed React Leaflet’s native zoom controls.
- Fixed the custom zoom controls to properly zoom the map.
- Improved UI layout so the search bar no longer overlaps with controls.
Notes:
- This PR only affects the map UI and zoom behavior.
- No business logic was modified.
- This fix happen only in the map page.
=> fix: zoom controls not working

.github/workflows/build-test.yml, package-lock.json, playwright.config.ts
Implements test sharding to significantly reduce CI/CD pipeline execution time by running Playwright tests in parallel across multiple machines.
- E2E Playwright tests currently take 43 minutes to complete
- Sequential test execution creates a bottleneck in the development workflow
- Slow feedback loop impacts developer productivity
Implemented Playwright test sharding feature to parallelize test execution across 4 machines, reducing total execution time to approximately 11 minutes.
- Configure GitHub Actions workflow to use matrix strategy with 4 shards
- Update Playwright configuration to use blob reporter for CI environments
- Add merge_reports job to consolidate test results from all shards
- Increase worker count from 1 to 2 for better parallelization within each shard
- Configure …
=> feat: implement Playwright test sharding for faster CI execution

public/locales/mag/common.json
Partial correction for the Maguindanawn ("Maguindanaon") locale at `public/locales/mag/common.json`.
The locale option contains vernacular translation.
- Me, a native speaker
- [1981 Publication of the Magindanawn-Pilipino-English Vocabulary by Summer Institute of Linguistics](https://www.sil.org/system/files/reapdata/12/56/99/12569941970962057337906899691526081588/mdh_Vocabulary_Magindanawn_English_Pilipino..._1981.pdf)
- Various Facebook posts from locals
=> fix: partial, proper translation for Maguindanaon language option

src/pages/government/GovernmentPageContainer.tsx, src/pages/government/departments/index.tsx
- media query will be based on container and not the page
- remove grouping background in mobile view.
P.S. 
unfortunately, precommit hook add lot of changes.
=> style: update responsiveness of government departments section

public/locales/ceb/visa.json
> ### Some English words do not directly translate to Cebuano so this is a mix of Cebuano-English.
**Example:**
- eVisa Portal
- Temporary Visitor's Visa (9a)
=> feat: Cebuano translation for visa.json

src/data/directory/constitutional.json, src/data/directory/departments.json, src/data/directory/diplomatic.json, src/data/directory/legislative.json
This PR updates all instances of "vacant" to "VACANT" across relevant data files for consistency.
Examples:
- Ethics and Privileges: VACANT
- Director General: VACANT
_See attached screenshots for before/after comparison._
=> fix: vacant uppercase

vite.config.ts
Excluding the `lucide-react` package from being pre-bundled was causing issues in some development environments, only showing a white screen. This makes `lucide-react` able to be pre-bundled again, solving the white screen issue.
=> build: do not exclude `lucide-react` from pre-bundling

src/lib/weather.ts, src/pages/data/weather.tsx, src/pages/government/legislative/components/LegislativeSidebar.tsx, src/types/index.ts
Fixes the hardcoded weather data issue in the weather page by displaying actual data from the OpenWeatherMap API.
- Added `humidity`, `windSpeed`, `pressure`, and `visibility` fields to the `WeatherData` type
- Updated `fetchWeatherData` function to retrieve and return these additional fields from the API
- Modified the weather page component to display actual data instead of hardcoded values
- Wind speed is converted from m/s to km/h for better readability
- Visibility is converted from meters to kilometers
Weather details (humidity, wind, pressure, visibility) were showing static hardcoded values:
- Humidity: Always 65%
- Wind: Always 12 km/h
- Pressure: Always 1013 hPa
- Visibility: Always 10 km
Weather details now display real-time data from the OpenWeatherMap API for each city.
Fixes …
=> fix: display real weather data instead of hardcoded values

src/components/search/MeilisearchInstantSearch.css
- Adjust `.ais-SearchBox-input` padding so text no longer overlaps the left search icon or the right-side reset/submit buttons.
- Behavior now matches the intended UX:
- Not focused: input adds extra left padding to clear the icon.
- Focused/typing: input uses normal left padding (no extra gap while typing).
- CSS: `src/components/search/MeilisearchInstantSearch.css`
- Base: `padding: 0.75rem 5rem 0.75rem 1rem;`
- When not focused: `form.ais-SearchBox-form:not(:focus-within) .ais-SearchBox-input { padding-left: 2.5rem; }`
- Keeps right padding to clear reset/submit buttons.
- Prevent input text from overlapping the search icon.
- Avoid a permanent left gap while typing, maintaining a natural caret position.
- Manual visual verification across focus/blur states.
- Confirmed no linter …
=> fix(search): prevent icon/input overlap 

src/data/directory/lgu.json
- Added Balanga City to Bataan LGUs so it appears in regional/local listings.
- Included mayor and vice mayor names
- Ensures the search and government pages can render Bataan’s complete LGU set without errors.
- Data sources include Wikipedia; I reside in Bataan and aimed to reflect accurate local information.
Balanga City was missing from the Bataan province LGU list, resulting in incomplete listings.
Balanga City is listed under Bataan with officials
- Data: `src/data/directory/lgu.json`
- Added `cities` array for `BATAAN PROVINCE` containing:
- `city`: Balanga
- `zip_code`: 2100
- `mayor.name`: RAQUEL FRANCIS D. GARCIA
- `vice_mayor.name`: FRANCIS ANTHONY S. GARCIA
- Completes the Bataan LGU set by including its component city.
- Primary reference: Wikipedia pages related to Balanga …
=> feat(lgu): add Balanga City under Bataan with mayor and vice mayor

.github/workflows/build-test.yml, e2e/homepage.spec.ts, package.json
- Some E2E tests are failing due to missing executables for firefox and webkit
- Tests related to BetterGov Homepage is failing as it uses a non-existing Playwright locator.
1. Fixed issue on playwright e2e pipeline where webkit and firefox executables are not found.
2. Fixed failing tests on e2e/homepage.spec.ts where close menu button is using incorrect Playwright locator (mobile view)
=> test: add missing executables on e2e pipeline with playwright

CONTRIBUTING.md
- Updated CONTRIBUTING.md to share ideas in Discord forum and Github Discussions page
We've moved all idea-related GitHub issues to the Discussions tab under the "Ideas" category. From now on, we would like to ask everyone who wants to share any new ideas to do so in one of these places:
Discord Ideas Forum: ⁠ideas
[GitHub Discussions](https://github.com/bettergovph/bettergov/discussions/categories/ideas)
See https://discord.com/channels/1415670958710325270/1418546658706329631/1421329022805348382
=> docs: Update Share ideas in Discussions

src/pages/government/legislative/[chamber].tsx
This renders email addresses for Secretariat Officials on legislative chamber pages as mailto: links, adds a decorative Mail icon (aria-hidden), and prevents layout overflow for long email strings with break-all styling and wordBreak. This is a UI-only fix; no data changes are included in this PR.
=> fix(legislative): render Secretariat email links and prevent overflow

functions/tsconfig.json, tsconfig.app.json, vite.config.ts
Added @ and @functions path aliases in tsconfig.json files and vite.config.ts
=> chore(config): use import aliases instead of relative imports

src/data/navigation.ts, src/pages/Discord.tsx
This PR updates the Discord link in the website footer. The previous link was outdated, preventing users from joining the community directly. This update ensures visitors are redirected to the correct and active Discord invite.
Fixes #356
- Updated the footer’s Discord link to the official and active invite URL.
=> fix(footer): update Discord link

src/data/services/social-services.json
This PR updates the outdated DSWD adoption service link to the correct URL. The old page indicated that the service has moved to a new address, so this change ensures users are redirected to the official and active resource.
- Replaced the old adoption URL with the updated link provided by DSWD.
=> fix(links): update outdated DSWD adoption service link

src/data/services/social-services.json
This PR removes the outdated Small Business Wage Subsidy (SBWS) Online application link from the Services section.
The Small Business Wage Subsidy (SBWS) program was a temporary COVID-19 relief measure under the Bayanihan to Heal as One Act (RA 11469). It ended in 2020 and was not extended or reopened. Users are advised to check the BIR, SSS, DOF, or DTI for current support programs.
- Removed the Apply for Small Business Wage Subsidy (SBWS) Online option from the Services section.
=> fix(services): remove outdated SBWS application link

src/data/services/education.json
This PR updates the PSRTI Training Courses service section to remove outdated information and ensure users are directed to the correct enrollment page. The previous title referenced "2019" and linked to a Google Form that is no longer accepting responses.
- Updated the title from "Register Online for 2019 PSRTI Regular Training Courses" to a more relevant version without a year reference.
- Replaced the outdated Google Form link with the official PSRTI website enrollment page.
=> fix(services): update PSRTI training title and enrollment link

README.md
- [BetterGov Docs](https://better-gov-docs.vercel.app/docs/about).
- This site pulls core docs from upstream BetterGov sync every 12hrs :
- `README.md`
- `CONTRIBUTING.md`
- `CODE_OF_CONDUCT.md`
- `TESTING.md`
- `ABOUT.md`
- Faster onboarding for new contributors
- Less time hunting for docs
- Consistent, readable documentation experience
=> docs(README): add Documentation section linking to BetterGov Document site

src/components/layout/Navbar.tsx
**Summary**
Adds line-height to navbar items to ensure that hover target area is big enough for large desktop screens.
**Review app**: https://bettergov-git-fix-hover-target-navbar-adobocorp.vercel.app
**Before**
https://github.com/user-attachments/assets/a103914f-8c0b-4dd2-bcf7-cb7a7ff13439
**After**
https://github.com/user-attachments/assets/d00721a5-edb1-4f2f-952d-4d344578f29d
**Other notes**
This pull request makes minor adjustments to the styling of navigation links in the `Navbar` component to improve visual consistency and alignment, primarily by adding the `leading-12` utility class and tweaking layout properties.
Styling improvements for navigation links:
* Added the `leading-12` class to the "Join Us", "Hotlines", and external "gov.ph" navigation links to ensure consistent …
=> fix(navbar): hover area when hovering

src/pages/government/GovernmentPageContainer.tsx
close #396 
This pull request makes targeted improvements to the scrolling behavior and sidebar positioning on the government index page. The main changes are focused on enhancing user experience when navigating to content and interacting with the sidebar.
***BEFORE***
***AFTER***
**Scrolling behavior improvements:**
* Updated the scroll logic in `GovernmentPageContainer.tsx` to use `offsetTop` instead of `getBoundingClientRect().top` and adjusted the scroll offset from -150 to -140 for more accurate positioning. Added a 100ms delay before scrolling to ensure the content is rendered.
**Sidebar positioning enhancements:**
* Modified the sidebar `<aside>` element to use `md:sticky` and `md:top-[8.25rem]` classes, making the sidebar sticky and better aligned for medium and larger screens.
=> fix(governments): scroll on main content rather than header

src/pages/philippines/holidays/PublicHolidays.tsx
This PR updates the holiday page to ensure information is always accurate without requiring manual yearly updates. #385 
- Minor refactor (move constant, component, outside the component)
- Page title now dynamically displays the current year (e.g., `Philippine Public Holidays 2025`).
- Holiday `day` values are computed dynamically based on the current year.
- Special non-working holidays are properly sorted for consistency.
=> fix : make page title and holiday details dynamic with current year

src/data/navigation.ts
Adds a "Documentation" link to the footer's "About" section for easy access to project docs.
- Added `{ label: 'Documentation', href: 'https://docs.bettergov.ph/' }` to footer navigation
- File: `src/data/navigation.ts`
=> feat: add documentation link to footer about section

.github/workflows/build-test.yml
- Pull playwright container instead of installing browsers each time CI is triggered
- This lessens the running time of the CI
- https://playwright.dev/docs/ci#via-containers
- https://mcr.microsoft.com/en-us/artifact/mar/playwright/about
Tested on https://github.com/DaijobuDes/bettergov/actions/runs/18271862080
and compare with https://github.com/bettergovph/bettergov/actions/runs/18269457731
=> chore(ci): use playwright docker image for E2E CI

Dockerfile, README.md, docker-compose.yml
This change enhances the local development workflow by introducing a dedicated development service in Docker Compose.
Previously, the Docker setup was optimized for production builds, requiring developers to rebuild the entire image to see changes. This commit introduces a new `dev` service that enables hot-reloading for a smoother development experience.
- Adds a `dev` stage to the `Dockerfile` that uses the Vite development server
- Adds a `dev` service to `docker-compose.yml` that mounts the source code as a volume, allowing changes to be reflected instantly without rebuilding
To use the new development environment, run:
```
docker-compose up dev
```
This change introduces a dedicated Docker Compose service for local development to provide a consistent, hot-reloading environment. While …
=> chore(docker): add hot-reloading for local development

src/components/layout/Navbar.tsx
Currently, the active navigation item in the navbar slightly shifts upward when selected. This happens because the active link adds a bottom border that isn't present on inactive links, changing the element's height.
**Fix**
To maintain consistent spacing and prevent the UI shift, I added a consistent bottom border to all navigation items:
- Inactive links now have a transparent bottom border.
- The active link retains the colored bottom border (as the visual indicator).
This ensures the navbar layout remains stable when switching between links.
**Before:**
https://github.com/user-attachments/assets/18bc3d33-4ca5-4da6-986f-76a00c218ed7
**After:**
https://github.com/user-attachments/assets/934c4594-e727-475b-8451-242395495a14
**Additional notes**
No visual regressions observed in other …
=> fix(navbar): remove shift caused by active border

src/components/home/JoinUsStrip.tsx
Currently, the "Join Now" Button is in the Tab size (min-width: 1023px). The Typography wraps around the button, but it doesn't quite look good on smaller devices.
Fix
To maintain a good-looking UI even in the smaller details. I aligned it more uniformly in the UI design for the button.
Before:
After:
I add the _whitespace-nowrap_ at the last class attribute
```CSS
<Link to='/join-us' 
className='inline-flex items-center gap-2 bg-yellow-300 text-gray-900 
px-4 py-1.5 rounded-full text-sm font-semibold hover:bg-yellow-200 transition-all 
transform hover:scale-105 whitespace-nowrap'>
{t('joinUs.joinNow')}
<ArrowRightIcon className='h-3 w-3' />
</Link>
```
=> fix(home): adjust Join Now button and UI typography tab size
