src/App.tsx, src/components/layout/Navbar.tsx, src/pages/Ideas.tsx
Adds support for project ideas
=> Ideas page

package-lock.json, package.json, src/components/home/InfoWidgets.tsx, tailwind.config.js
- Grid columns should adapt to size of parent
- Add extra dependency because of old tailwind version which will be removed after updating to tw version 4.
=> fix: Improve responsiveness of weather widget

LICENSE, src/pages/Ideas.tsx
Add license to the repo: https://creativecommons.org/publicdomain/zero/1.0/
=> docs: add license

scripts/fetch-hrep.js, src/App.tsx, src/data/directory/house_members.json, src/data/directory/legislative.json, src/data/directory/party_list_representatives.json, src/pages/government/legislative/components/LegislativeSidebar.tsx, src/pages/government/legislative/party-list-members.tsx
Closes #56 
Should now show the updated list
- 20th congress
- updated speakership
- updated committee list
- Members by Party List page
=> House of Representatives list should now reflect the 20th congress

src/pages/travel/visa/index.tsx
Description:
Visa Information Section had broken responsiveness due to the hero section component not having appropriate padding
UI Enhancements:
Added padding to hero section
Made Quick Visa Check component align to center on smaller screen size
Screenshots:
Current Implementation:
Fix:
=> fix: visa-information hero section broken responsiveness by adding padding

.github/actionlint-matcher.json, .github/workflows/github-action-linter.yml
Preempting before anything breaks.
=> feat: add github action/workflow linter

src/data/directory/lgu.json
Description:
Added missing davao city details in local government unit 
Resolves: #88
=> feat: added davao city to lgu info

src/pages/government/layout.tsx
**Summary**
Removed redundant government branch section below the hero-section
Current Implementation:
Fix:
=> fix: removed redundant government branch components below hero section

src/components/ui/SelectPicker.tsx, src/pages/travel/visa/index.tsx
- Replace desktop-only search input with responsive SelectPicker component in hero section
- Implement a searchable dropdown for country selection on mobile/tablet devices  
- Maintain existing desktop functionality with the country list sidebar
- Add proper accessibility attributes and keyboard navigation
- Ensure consistent UX across all screen sizes
**Changes:**
- Created new `SelectPicker` component with search, clear, and positioning features
- Updated hero section to use responsive search (desktop input + mobile SelectPicker)
- Updated main content area to use SelectPicker on mobile/tablet (xl:hidden)
- Preserved desktop search input for larger screens (hidden xl:block)
- Added proper TypeScript interfaces and a responsive design
- Fixes to lint issues
Closes #123
**No changes made …
=> fix(ui): improve visa quick search and hero section in visa page

src/pages/flood-control-projects/index.tsx, src/pages/flood-control-projects/shared-components.tsx
Summary:
- Fixed an issue on `FilterDropdown` as Stated in this #87 
- Commented `HitProps` and `Hit` component as it was not used in the code
=> fix: update dropdown Filter toggle functionality

README.md, docker-compose.yml
This PR adds comprehensive Docker documentation to the README and includes a `docker-compose.yml` file for easier container management.
- ✅ Added complete Docker section to README.md with:
- Building instructions
- Running commands
- Docker Compose usage
- ✅ Created `docker-compose.yml` for simplified container management
- `README.md` - Added Docker documentation section
- `docker-compose.yml` - New file for container orchestration
- Container name is set to "bettergov" for consistency
- Port mapping: 8080 (external) → 80 (internal)
- Was having issues with `npm run dev` (blank page due to ad blocker blocking Lucide React icons), so Docker provides a reliable alternative for local development
=> docs: Add comprehensive Docker documentation and setup

src/App.tsx
Closes https://github.com/bettergovph/bettergov/issues/42
=> fix(routes): set default index route for philippines & travel

src/pages/philippines/holidays/PublicHolidays.tsx
- Addressed issue #141 
- Link to Page in Site: https://www.bettergov.ph/philippines/holidays
Current image
UI in Local Dev Env after change
=> style: move disclaimer at the top of the page

src/pages/government/constitutional/components/ConstitutionalSidebar.tsx, src/pages/government/constitutional/index.tsx
- corrected condition for adding highlight
- add default selected by going to the first item in the offices
Screenshot below shows that highlighted is now working
Fix #169
=> fix highlight and default selected for constitutional bodies

src/data/service_categories.json, src/data/services/tax.json
Should now show the tax directory & calculator in the Tax Government Services section
=> Add the tax directory to the list of tax services

src/pages/government/legislative/components/LegislativeSidebar.tsx
- remove useParams
- use isActive utility function and provide correct path name
Fix Issue #191 
https://github.com/user-attachments/assets/af76359e-d3ac-442b-a0b5-3bf25d9d23f6
=> fix highlight for legislative branch

src/pages/government/legislative/components/LegislativeSidebar.tsx
- Fix code style issues in LegislativeSidebar component
- Ensures consistent formatting across the codebase
- Resolves prettier linting errors
=> style: fix prettier formatting in LegislativeSidebar.tsx

src/pages/flood-control-projects/contractors/[contractor-name].tsx, src/pages/flood-control-projects/map.tsx
=> fix: map marker

public/locales/en/flood-control-projects.json, public/locales/fil/flood-control-projects.json, src/pages/flood-control-projects/index.tsx
translate flood control project page
=> feat: translate flood control project page

src/pages/services/index.tsx
- Add subtle left border lines to subcategories when parent categories are expanded for better visual hierarchy and UX.
- Lines provide clear visual grouping to help users understand which subcategories belong to which parent category.
- Behavior now matches modern UI patterns for hierarchical navigation.
- React: `src/pages/services/index.tsx`
- Added conditional CSS classes: `relative pl-3 before:absolute before:left-0 before:top-0 before:bottom-0 before:w-0.5 before:bg-gray-200`
- Applied only when `selectedCategorySlug === category.slug` (category is expanded)
- Uses CSS pseudo-element for full height coverage
- Improve user experience by providing visual hierarchy cues
- Reduce cognitive load when navigating through service categories
- Use subtle styling that doesn't interfere with …
=> feat(Categories): add visual lines to expanded categories

src/data/directory/lgu.json
- Added Tarlac City to Tarlac Province City List
- Fixes Issue #238
=> feat(lgu): Add Tarlac City details to lgu.json

src/components/home/InfoWidgets.tsx, src/pages/data/weather.tsx
=> feat(weather): add openweathermap attribution

src/data/services/certificates-ids.json
=> fix(web): change umid id to umid

.github/workflows/build-test.yml, Dockerfile
This PR includes the following:
- Update the author to include the group's email address
- Add a comment to explain the intent to the build step
- Add an image tag with the commit hash
- Arm64 docker image build is slow, removing it for now since it's not in use anyway
=> feat(ci): img tag using commit sha, update img author

e2e/critical-flows.spec.ts, e2e/navigation.spec.ts, e2e/performance.spec.ts, e2e/utils/device.ts, e2e/utils/navbar.ts
- Attempt to fix failed E2E tests due to UI changes
- Added "helper" functions for use in E2E
Skipped `performance.spec.ts` due to flakiness of the tests. Discussion can be found on `#qa-testers` [channel](https://discord.com/channels/1415670958710325270/1419325350550179861/1421418785054916650)
@batuzai04123 will work on `accessibility.spec.ts` and `homepage.spec.ts` and will be on a separate PR. [related message on discord](https://discord.com/channels/1415670958710325270/1419325350550179861/1421198500158505011)
```
15 failed
[chromium] › e2e\accessibility.spec.ts:5:3 › Accessibility › homepage should not have accessibility violations
[chromium] › e2e\accessibility.spec.ts:15:3 › Accessibility › services page should not have accessibility violations
[chromium] › …
```
=> Fix E2E tests

src/data/navigation.ts
=> fix: Update Official Gov.ph link to use the correct URL #352

src/pages/travel/visa-types/[type].tsx, src/pages/travel/visa-types/index.tsx, src/pages/travel/visa-types/visa.util.ts
Extract duplicate getCategoryIcon function into shared utility file
=> chore(visa): add visa.util.ts for reusable util func

.prettierignore
=> chore(prettier): update ignore rules to include docs formatting

src/data/services/education.json
This PR updates the SHS Voucher Program title in the Services section to make it more timeless and relevant. The previous version included a specific school year (2019–2020), which can quickly become outdated.
- Updated the title from _**"Apply Online for SHS Voucher Program for School Year 2019-2020"**_ to _**"Apply Online for SHS Voucher Program"**_
=> refactor(services): simplify SHS voucher program title

package-lock.json, src/pages/government/constitutional/index.tsx, src/pages/government/departments/[department].tsx, src/pages/government/legislative/[chamber].tsx
adjust text alignment across government page
=> style(government): adjust misaligned government details

public/locales/en/about.json, public/locales/en/common.json, src/components/layout/Footer.tsx, src/components/layout/Navbar.tsx, src/data/navigation.ts, src/pages/about/index.tsx, src/types/index.ts
=> Add 'Our Projects' in the Navbar and Footer
